spring:
    application:
        name: eurekaServer
    security:
        basic:
            enabled: true
        user: # Ideal é utilizar em variavel de ambiente, mas para aprendizado deixei fixo
            name: ms-eureka-user
            password: 123456


server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
