spring:
    application:
        name: eurekaServer
    security:
        basic:
            enabled: true
        user:
            name: ${EUREKA_SERVER_USER}
            password: ${EUREKA_SERVER_PASS}

server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
